### ISSUE TITLE
Gamebreaking Bug for Ad Astra

### ISSUE THREAD

**Issue by KavisKryptic** [MerchantPug/apugli#67] opened 2023-12-27 03:07 UTC
When in forge, 1.20.1:
Latest version of Ad Astra (1.15.5)
Latest version of Botarium (2.2.1)

With origins and toomanyorigins present, space suits cannot contain oxygen when placed in player's inventory. Makes it so the main content of Ad Astra would be inaccessible (since, you know. You need oxygen to breathe in the space dimensions/planets). This is only an issue present when TooManyOrigins is present.

Really strange, I was testing for awhile trying to figure out which mod was the culprit (or maybe it's Ad Astra's end, I'm not sure), but definitely did not expect this mod xD

Please do let me know if you learn what's causing the issue, I'm extremely curious!

https://streamable.com/2sekb9 (Clip of the issue)

**Comment by ChrysanthCow** [comment] 2023-12-27 12:35
which version of Origins and TooManyOrigins are you on?

**Comment by ChrysanthCow** [comment] 2023-12-27 12:39
This is basically a "something is breaking capabilities™️" issue.

**Comment by ChrysanthCow** [comment] 2023-12-27 13:03
Okay, confirmed the bug exists with the latest version of TMO

**Comment by KavisKryptic** [comment] 2023-12-28 06:37
Oh yeah sorry forgot to clarify it was the latest version of TMO

**Comment by ChrysanthCow** [comment] 2023-12-28 07:12
I think I'll handle this at a later date, I'm a little busy handling another mod atm. You should be safe to uninstall TMO for the time being.

Obviously not the ideal solution, I know, but idk when ill get to fixing this.

**Comment by ChrysanthCow** [comment] 2024-02-21 22:48
Okay, so I'm pretty sure I've figured out this issue. Once I'm done updating Apugli (where the issue lied, TMO uses this library for a majority of content), TooManyOrigins will have an update that fixes this.

Edit: Haven't figured it out yet.

**Comment by ChrysanthCow** [comment] 2024-02-22 04:26
This seems to be a bug with Origins Forge too, So I'll make an issue over there.

**Comment by ChrysanthCow** [comment] 2024-02-22 07:09
nvm, apparently the bug I thought was wrong with Origins Forge was actually a bug with Ad Astra's latest version, will test on an older Ad Astra version.

**Comment by ChrysanthCow** [comment] 2024-02-23 10:30
Fixed in local after I rewrote everything involving the thing that broke it. Will be added in Apugli and TMO's next update.

**Closed as completed** 2024-03-06 16:04 UTC
Labels: bug, mc: 1.20
