### ISSUE TITLE
Oddities with `apugli:modify_equipped_item_render`

### ISSUE THREAD

**Issue by CyraLX** [MerchantPug/apugli#43] opened 2023-06-28 16:24 UTC
Don't know how to really describe the issue per say but this clearly doesn't work:

Example:
Power on the Player is:
```json
{
    "type": "apugli:modify_equipped_item_render",
    "slot": "mainhand",
    "scale": 1.0,
    "override": true,
    "merge_with_held": false,
    "condition": {
        "type": "apoli:equipped_item",
        "equipment_slot": "mainhand",
        "item_condition": {
            "type": "apoli:ingredient",
            "ingredient": {
                "item": "minecraft:golden_hoe"
            }
        }
    },
    "stack": {
        "item": "minecraft:golden_hoe",
        "tag": "{Enchatnemtns: [{id: \"minecraft:loyalty\", lvl: 1}]}",
        "amount": 1
    }
}
```
This is supposed to replace the render of a Golden Hoe with an enchanted Golden Hoe however it doesn't do it in Third Person. But what is more weird in First Person it creates a render of a Golden Hoe in both Off Hand and Main Hand even thought it only targets the Main Hand.

**Comment by ChrysanthCow** [comment] 2023-06-28 22:52
Looking into this now, at first glance, your tag is wrong but I can confirm that something is wrong here.

`"{Enchantments: [{id: \"minecraft:loyalty\", lvl: 1}]}"`
This above should be fixed, you had a typo with Enchantments.

**Comment by ChrysanthCow** [comment] 2023-06-28 22:56
Update, third person seems to work fine once I fixed the item tag. First person's rendering is still unintended.

**Comment by ChrysanthCow** [comment] 2023-06-28 22:59
And this was an easy fix. The issue was that I forgot to change the slot check from mainhand to offhand when handling offhand items.

Will be fixed next update.

**Closed as completed** 2023-06-29 08:18 UTC
Labels: bug
