### ISSUE TITLE
`apugli:edible_item` incompatibility with Collective

### ISSUE THREAD

**Issue by Davithy** [MerchantPug/apugli#9] opened 2022-05-18 01:55 UTC
Less of a bug and more of a feature request. As the title says, I'd like for the edible item power to work with the minecraft:used statistic so that it can be used to track for achievements! Probably incredibly niche ask so it's okay if it's not something you end up working on, but thought I'd suggest!

**Comment by ChrysanthCow** [comment] 2022-05-18 08:56
Thanks for suggesting this!

I was suggested this in my own discord and was going to implement it but I never got around to it and forgot about it

**Comment by Davithy** [comment] 2022-05-18 12:08
Haha, that was actually me! I wanted to formally place it in as a request here and be official about it. I'll keep an eye out on the future updates!

**Comment by ChrysanthCow** [comment] 2022-06-02 11:31
This already seems to be a feature in the latest Apugli (ever since I refactored the edible item code)

**Comment by Davithy** [comment] 2022-06-02 12:03
Awesome!! Thanks for letting me know, I'll happily close this "issue" 👍

**Comment by ChrysanthCow** [comment] 2022-06-02 12:18
I'm fixing some bugs with it rn but it should be functional

**Comment by Davithy** [comment] 2022-06-03 00:21
so in my short time testing it, I have found that in an isolated environment with just origins and apugli, it works great just as advertised, but after adding the mods I intend to use in a pack, something seems to prevent the edible item power from working properly. Essentially, the player will act as though the item is being eaten, but the item will not be eaten, hunger will not be given, and the item used counter doesn't increase. I'll try to find the mod that's causing this issue, but I won't reopen this issue quite yet unless I can confirm it's an issue with apugli or the unnamed mod.

**Comment by Davithy** [comment] 2022-06-03 01:36
okay, I believe it's the collective api made by Serilum. Removing the collective-fabric-1.18.x-4.26.jar from my mods seems to properly give the edible item power its functions back, and replacing it should replicate the issue if you want to give it a check!

**Comment by MerchantPug** [comment] 2022-06-03 21:37
>

**Comment by ChrysanthCow** [comment] 2022-06-03 21:50
https://github.com/ricksouth/serilum-mc-mods/issues/1094

I've filed a bug report for Collective.
I'll be increasing my mixin's priority in the meantime for the next update.

**Comment by ChrysanthCow** [comment] 2022-09-18 03:24
https://github.com/ricksouth/serilum-mc-mods/issues/1094#issuecomment-1250062010

Apparently it has been fixed here. I'll check in a test world to make sure nothing is broken on my end before closing this issue.

**Comment by ChrysanthCow** [comment] 2022-09-18 04:02
Confirmed fixed.

**Closed as completed** 2022-09-18 04:02 UTC
Labels: bug, compatibility
