### ISSUE TITLE
Weird interaction between Better Combat, MC Dungeons Weapons and TooManyOrigins

### ISSUE THREAD

**Issue by finnglink** [MerchantPug/apugli#54] opened 2023-08-25 11:26 UTC
Hey!
I'm having a really weird issue with my little pack, which seems to come from some sort of correlation between the three named mods: When I equip a two handed weapon form MCDW / BC while holding something in my offhand, that item gets deleted. And this seems to be caused by TMO, removing that fixes it. Any ideas why the might be happening?

**Comment by ChrysanthCow** [comment] 2023-08-25 13:27
Better Combat issue and duplicate of https://github.com/MerchantPug/apugli/issues/51.

I can really only bandaid fix this in Apugli (a library that TooManyOrigins uses) by making the check specifically for `ItemStack.EMPTY`, rather than `ItemStack#isEmpty`.

That mod should probably not return non empty ItemStacks with 2h weapons as empty to avoid situations like this in the future.

A more detailed explanation can be found below:
https://github.com/ZsoltMolnarrr/BetterCombat/issues/268#issuecomment-1679088344

**Comment by ChrysanthCow** [comment] 2023-08-25 13:45
Will be fixed next update.

**Comment by finnglink** [comment] 2023-08-25 13:47
@MerchantPug awesome! Feel free to ping me to test it, and I'll just drop it in my pack to check

**Comment by ChrysanthCow** [comment] 2023-08-26 10:03
Re-opening as it was agreed upon that the fix would be cleaner if it were done on my end.

**Comment by ChrysanthCow** [comment] 2023-08-26 10:06
and my previous commit didn't actually fix it... At least it got me to optimise everything a bit.

**Closed as completed** 2023-08-26 10:07 UTC
Labels: bug, compatibility, mc: 1.19.2, mc: 1.20, loader: fabric, loader: forge/neoforge

**Comment by ChrysanthCow** [comment] 2023-08-26 10:13
Fixed, it scared me initially because I didn't know how the mechanic worked, but your items should now be preserved in your offhand. If any of you have a server with players, please give them back their items that they lost due to this bug.

![javaw_LOdci3X6BQ](https://github.com/MerchantPug/apugli/assets/81167232/73c5dfb8-9fbd-4833-9b5e-220b45877414)

**Comment by ChrysanthCow** [comment] 2023-08-26 11:08
Fixed in 2.6.5. Will be fixed in TMO 0.9.3 and 1.0.0-beta.18
